# Generated by Django 3.2.7 on 2021-09-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_ip', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rating',
            table='rating',
        ),
    ]
