# Generated by Django 3.2.7 on 2021-09-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_ip', '0004_alter_rating_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='project_image',
        ),
    ]
