# Generated by Django 3.2.7 on 2021-09-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ip', '0006_auto_20210924_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, default=0, upload_to='images/projects/'),
        ),
    ]
